### ISSUE TITLE
Use local images instead of quay.io by default

### ISSUE THREAD

**Issue by jajik** [modcluster/mod_proxy_cluster#125]
The default should be:

* local images
* no upload to anywhere
* add option to change that (basically we have that, maybe add a function for pushing?)
* update README

**Comment by rhusar** [comment]
What would be the use case for pushing partial test artefacts remotely? I am failing to see one.

**Comment by jajik** [comment]
Well these are not test artefacts necessarily, it's just tomcat/httpd with mod_cluster/mod_proxy_cluster, so why not?
