### ISSUE TITLE
Testsuite: integrate a proper testing framework rather than using set of custom scripts

### ISSUE THREAD

**Issue by rhusar** [modcluster/mod_proxy_cluster#130]
e.g. use bats.

**Comment by jajik** [comment]
Just to mention, the current testsuite tries to be POSIX compliant, which bats is not (?). We might consider [ShellSpec](https://github.com/shellspec/shellspec), which should be.

However, I don't know any of these, so I'll have a look and will report about it.

**Comment by rhusar** [comment]
@jajik When you have a minute, if you can look into what upstream Apache and / or it's modules use that would be interesting too. I am going to just assume it's something home brewed and not portable.

**Comment by jajik** [comment]
That's a good idea. Will do.

**Comment by jajik** [comment]
So, it turns out that httpd uses (maybe a bit surprisingly) pytest for some testing (see [README.pytest](https://github.com/apache/httpd/blob/trunk/test/README.pytest)).  That looks interesting, although I don't like python very much. Personally, I don't think rewriting tests we have into pytest is the way to go, I would prefer just adapting them to ShellSpec/bats, but for new tests it might be an option.

**Comment by rhusar** [comment]
> So, it turns out that httpd uses (maybe a bit surprisingly) pytest for some testing (see [README.pytest](https://github.com/apache/httpd/blob/trunk/test/README.pytest)). That looks interesting, although I don't like python very much. Personally, I don't think rewriting tests we have into pytest is the way to go, I would prefer just adapting them to ShellSpec/bats, but for new tests it might be an option.

If we are talking about preferences I would strongly to prefer to have them in Java. I am under impression that what we have now can be done in Java quite with ease.

**Comment by jfclere** [comment]
https://github.com/apache/httpd-tests is the one I contributed.

**Comment by jajik** [comment]
That looks like Perl! Definitely prefer that over Python, I'll have a look, thanks!
