### ISSUE TITLE
Testsuite: investigate usage of portOffset rather than `sed`ing the ports

### ISSUE THREAD

**Issue by rhusar** [modcluster/mod_proxy_cluster#140]
Perhaps that would simplify things.

Context: https://github.com/modcluster/mod_proxy_cluster/pull/137#issuecomment-1698820831

**Comment by jajik** [comment]
There are multiple things:

* Function [`tomcat_start`](https://github.com/modcluster/mod_proxy_cluster/blob/35de1cd8c0905976f49a0a2d016f4193f2655625/test/includes/common.sh#L114) that allows us to set various ports.
    * Here we could use `portOffset` feature instead of our manual offsetting.
    * That might interfere with the ability to set ports manually – can we easily apply the offset for *some ports* only?
* Part of the tomcat docker image script that tries to find an empty shutdown port ([here](https://github.com/modcluster/mod_proxy_cluster/blob/35de1cd8c0905976f49a0a2d016f4193f2655625/test/tomcat/start.sh#L6)).
   *  We want to drop this probably (i.e., drop this section + check testsuite for `tomcat_shutdown_port=yes` and set it explicitly or use the mechanism above).

**Comment by jajik** [comment]
I can confirm that `portOffset` would simplify things. Although, it would be possible to preserve our ability to set ports manually, after going through our test base I would say it is not necessary. I'll prepare a PR once [MODCLUSTER-798](https://github.com/modcluster/mod_cluster/pull/735) gets resolved.
