### ISSUE TITLE
Testsuite: all tomcat versions are sharing the same config (and deployment)

### ISSUE THREAD

**Issue by rhusar** [modcluster/mod_proxy_cluster#141]
This will eventually break, when tomcat adds features that are not supported by previous versions, similar to e.g. jakarta namespace for the deployment.

Ideally, these should have configuration and possibly deployments specific to them. Anyway, so far low priority / optional.

**Comment by jajik** [comment]
That's a good point. We might also just add a variable with the config file the same way we do it for the version.
