### ISSUE TITLE
Add license and topics to the repository's overview

### ISSUE THREAD

**Issue by jajik** [modcluster/mod_proxy_cluster#144]
It looks like this repository does not have license and topics set the same way as [mod_cluster](https://github.com/modcluster/mod_cluster) has (look at the side panel). It would be nice to have it set up the same way here too.

**Comment by rhusar** [comment]
@jajik Thanks for bringing this up, I will fix this (there is actually more at play here that needs to be done (in progress) regarding the licence itself).

**Comment by jajik** [comment]
Is there something missing? Maybe adding some topics, but other than that it seems fine now.

**Comment by rhusar** [comment]
@jajik Checking - the license is all good now everywhere, we just haven't defined any topics. I have just added a couple. We can resolve now.
