### ISSUE TITLE
Testsuite: Investigate failures and make it more stable

### ISSUE THREAD

**Issue by jajik** [modcluster/mod_proxy_cluster#149]
The testsuite fails occasionally, mainly main tests and JBCS-1236 tests. Investigate and fix those instabilities if possible.

**Comment by jajik** [comment]
It seems that at least some of the failures are linked to tomcat's connector ports. That will be addressed with #140  using `portOffset`.

**Comment by rhusar** [comment]
> It seems that at least some of the failures are linked to tomcat's connector ports (more precisely to the custom mechanism we use). That will be addressed with #140 using `portOffset`.

I will to to get those fixed next week.

**Comment by jajik** [comment]
Ack, thank you.

**Comment by jajik** [comment]
Given the changes we made since opening this issue and the fact that we don't experience random fails anymore, I'm closing the issue now.
