### ISSUE TITLE
Build doxygen docs

### ISSUE THREAD

**Issue by jajik** [modcluster/mod_proxy_cluster#161]
After #158 gets finished, we should be able to easily generate doxygen docs. We might even run it in in CI.

**Comment by rhusar** [comment]
Right and publish them in a similar fashion to javadoc on the docs website - https://docs.modcluster.io/apidocs/

**Comment by jajik** [comment]
ref https://github.com/modcluster/docs.modcluster.io/pull/127

**Comment by rhusar** [comment]
We can do a few things here:

1. build in CI and fail when docs are broken - we don't typically do this in our Java projects but we may want to do it here; I would +1 
2. build and publish automatically on push or release - not worth the effort so -1

**Comment by jajik** [comment]
I guess we can go with 1), more checks won't hurt us. I don't think it's necessary to publish it automatically as we don't usually change the interfaces. However, we can include it into the CI's artifact (it will be built anyway as a part of the 1)).

**Comment by rhusar** [comment]
Sounds like a plan.

**Comment by jajik** [comment]
Ok, I'll do it.
