### ISSUE TITLE
version_data used shared memory directly and is broken on windows.

### ISSUE THREAD

**Issue by jfclere** [modcluster/mod_proxy_cluster#187]
Actually that is just a counter and probably atomic should be used there.

**Comment by jfclere** [comment]
dirty work-around:
<pre>
diff --git a/native/mod_manager/mod_manager.c b/native/mod_manager/mod_manager.c
index ccef471..79a572f 100644
--- a/native/mod_manager/mod_manager.c
+++ b/native/mod_manager/mod_manager.c
@@ -537,7 +537,8 @@ static void normalize_balancer_name(char *balancer_name, const server_rec *s)
 static APR_INLINE int is_child_process(void)
 {
 #ifdef WIN32
-    return getenv("AP_PARENT_PID") != NULL;
+    // return getenv("AP_PARENT_PID") != NULL;
+    return 0;
 #else
     return 0;
 #endif
</pre>

**Comment by jajik** [comment]
I can confirm that this helps.
