### ISSUE TITLE
Error manager_init: create_share_version failed on Windows with httpd 2.4.58

### ISSUE THREAD

**Issue by zerikv** [modcluster/mod_proxy_cluster#203]
Hello,

Because I need mod_cluster modules working with Apache httpd 2.4.58 on Windows, I've tried to build the "main" branch [087cc48](https://github.com/modcluster/mod_proxy_cluster/commit/087cc48b953c53690b150c89875d848ab5fa18d7) with the environment :
- httpd-2.4.58-240131-win64-VS17 (from Apache Lounge)
- Microsoft Visual Studio Community 2022 Version 17.5.3
- Microsoft .NET Framework Version 4.8.04084

The compilation is fine and 4 modules .so are created.

But when the httpd start (as a service) the following erreur occurs :

```
[Mon Feb 19 09:39:10.497639 2024] [:emerg] [pid 50512:tid 356] (OS 2)The system cannot find the file specified.  : manager_init: create_share_version failed
[Mon Feb 19 09:39:10.497639 2024] [:emerg] [pid 50512:tid 356] AH00020: Configuration Failed, exiting
[Mon Feb 19 09:39:10.591659 2024] [mpm_winnt:crit] [pid 24648:tid 324] AH00419: master_main: create child process failed. Exiting.
```
In the directory `C:/Httpd/logs/`, no files prefixed `manager.` have been created as usual.

I have also tried to apply this fix : https://github.com/modcluster/mod_proxy_cluster/pull/189/files on the main branch 
because it seems related but no luck, at the start of the httpd service there is a loop with the following errors : 

```
[Mon Feb 19 23:41:14.742326 2024] [mpm_winnt:notice] [pid 31556:tid 332] AH00428: Parent: child process 26536 exited with status 3221225477 -- Restarting.
...
[Mon Feb 19 23:41:22.377712 2024] [:emerg] [pid 55256:tid 348] manager_child_init: get_mem_node C:/Httpd/logs/manager.node failed: No shared memory is currently available
```
Any advice will be appreciated.

**Comment by rhusar** [comment]
Thanks for the report, we are aware of the issue and the fix should be available with the next Apache httpd release. @jfclere will have more context.

**Comment by jajik** [comment]
Hi, httpd 2.4.59 was released. With the #189 change in `main`, you should be able to use mod_proxy_cluster on Windows.

Closing now as fixed.
