### ISSUE TITLE
Support running testsuite on Windows

### ISSUE THREAD

**Issue by jajik** [modcluster/mod_proxy_cluster#204]
The testsuite is based on posix shell and docker containers, so it might be relatively compatible even with Windows. However, httpd with mod_proxy_cluster also runs within a container, therefore, if we would like to test on Windows, we should

* check out how docker works on Windows
* adapt the container file to Windows
* run the testsuite on Windows (in CI)

**Comment by jajik** [comment]
Ok, so after some digging it seems this is not possible.

In general, running Windows containers on Windows is possible, using Windows Server 2022 it might be even possible to run them side by side with Linux containers (using wsl). However, GH Actions doesn't support running containers on Windows at all (see https://github.com/orgs/community/discussions/25491).

**Comment by rhusar** [comment]
Well, as I mentioned on the call - the whole point of running on windows would be for the http process to run natively on windows rather than in a container. So the issue is still valid.

Moreover, the GHA limitation is not a blocker - this is limitation of the GHA runners, we can always provide our own and more importantly, the testsuite can be run outside of GHA.

**Comment by jajik** [comment]
> Well, as I mentioned on the call – the whole point of running on windows would be for the http process to run natively on windows rather than in a container. So the issue is still valid

We were talking about running it within a Windows container because that seemed the easiest.

> Moreover, the GHA limitation is not a blocker - this is limitation of the GHA runners, we can always provide our own and more importantly, the testsuite can be run outside of GHA.

If we have resources at our disposal to do such a thing (running it outside, I'm not sure that self-hosted runners are worth it), we can try to do it. But then opening a JIRA would be more appropriate, imho.
