### ISSUE TITLE
CI: Drop macos runner for clang-format

### ISSUE THREAD

**Issue by jajik** [modcluster/mod_proxy_cluster#222]
Once Ubuntu 24.02 will come out, it should have clang-format new enough to drop the macOS runner.

**Comment by rhusar** [comment]
Just to state the obvious, it also depends when github switches ubuntu-latest to that released ubuntu version. I dont know whats their policy on that, but I would assume they only pick the LTS releases.

**Comment by jajik** [comment]
Sure, they have it in the roadmap for the Q2.
