### ISSUE TITLE
Handle `nodeinfo.offset` better

### ISSUE THREAD

**Issue by jajik** [modcluster/mod_proxy_cluster#265]
1) The `offset` is not necessary to keep in each instance, it is a compile time constant.
    - Done
2) Fix offset computation (`unsigned long` vs `int`). 
    - Done
3) Additionally, is the `offset` needed at all? Are there configurations where `nodeinfo.stat` won't be aligned?

**Comment by jajik** [comment]
After some investigation, I think the offset is needed because of a little more exotic architectures (see [MODCLUSTER-831(https://issues.redhat.com/browse/MODCLUSTER-381)). Basically, we want to preserve 64-bit alignment even on 32-bit systems, so this is indeed needed.

What we might consider is changing `SIZEOFSCORE` which seems unnecessarily big (currently, it's 1700, the `proxy_worker_shared` structure has less than 1500 bytes on my system – imho we might do something like `#define SIZEOFSCORE ALIGNED_PROXY_WORKER_SHARED_SIZE + 8` or so).

fyi @jfclere

**Comment by rhusar** [comment]
@jajik Perhaps add a source code comment to describe this for future coders?

**Comment by jajik** [comment]
That's not a bad idea. Let's wait for JFC and do it with the possible change of `SIZEOFSCORE`.
