### ISSUE TITLE
undefined symbol: proxy_run_check_trans

### ISSUE THREAD

**Issue by Gninieb** [modcluster/mod_proxy_cluster#32]
Ubuntu 20.04., Apache/2.4.41 ==>
Cannot load /usr/lib/apache2/modules/mod_proxy_cluster.so into server: /usr/lib/apache2/modules/mod_proxy_cluster.so: undefined symbol: proxy_run_check_trans

**Comment by jfclere** [comment]
you need at least 2.4.47

**Comment by jfclere** [comment]
https://github.com/apache/httpd/blob/2.4.x/CHANGES#L116
