### ISSUE TITLE
Is there any way to choose which node should be used

### ISSUE THREAD

**Issue by DragoMlakar** [modcluster/mod_proxy_cluster#56]
Trying to figure out how to add some node to cluster that would be visible just to users that set some secret, cookie.
Is there any neat existing solution? Something with sticky cookies? @jfclere @rhusar 
So we can for example add node to prod and just QA can test it before all other users.

**Comment by jfclere** [comment]
The cookie is filled by the server (node)  so you can't use it for that. Normally a different context is used, you can protect the context using Apache httpd limitation for example require a valid user.

**Comment by DragoMlakar** [comment]
Ok. Thank you for feedback.

**Comment by rhusar** [comment]
@DragoMlakar As @jfclere says, we don't have a top level feature to do this, though I think we could and perhaps should have. Please open a feature request. 

Using a separate context (or host perhaps?) seems to be the best way to do this.

@jfclere Should we provide an example how to setup that 'valid user' workaround, e.g. in docs or do we not want to promote it?

Another workaround that comes to mind is starting the node as disabled / with `load="0"` and then manually creating a user session that contains route to the disabled node? This way, normal new requests won't be routed to that node only the 'test ones'.

**Comment by aogburn** [comment]
@rhusar Yes, the new node could be configured and launched with modcluster's auto-enable-contexts set to false so it is disabled and QA members can access and test it manually initially adding a ".route" value JSESSIONID cookie to their requests.  Otherwise, separate contexts or hosts with access control should be the way to go.

**Comment by jfclere** [comment]
the  'valid user' is not mod_cluster but standard httpd configuration stuff see  https://httpd.apache.org/docs/2.4/howto/auth.html and just require a valid user for the context.

**Comment by DragoMlakar** [comment]
> @rhusar Yes, the new node could be configured and launched with modcluster's auto-enable-contexts set to false so it is disabled and QA members can access and test it manually initially adding a ".route" value JSESSIONID cookie to their requests. Otherwise, separate contexts or hosts with access control should be the way to go.

We can try with this auto-enable-contexts false but not sure how to set proper JSESSIONID value. Can you give some example?

**Comment by aogburn** [comment]
This would just be adding a JSESSIONID cookie on the client with a value like ".instanceidfornewnode" to be sent in the requests to httpd.  ".instanceidfornewnode" would be the instance-id value used by the new node you want the request stickied to (which would be the name for the balancer member shown in the /mod_cluster_manager page).

**Comment by DragoMlakar** [comment]
@rhusar  Is this somehow releated to this https://issues.redhat.com/browse/MODCLUSTER-780 ? 
It would be nice to have it with this additional cookie.

**Comment by rhusar** [comment]
> @rhusar Is this somehow releated to this https://issues.redhat.com/browse/MODCLUSTER-780 ? It would be nice to have it with this additional cookie.

Yes, it is somewhat related - so basically if we supported affinity stored in a separate cookie you could just edit a single cookie with the new route, rather than editing the JSESSIONID value.

**Comment by DragoMlakar** [comment]
@rhusar  Any progress on this? It would be nice to have this feature for different production scenarios.
