### ISSUE TITLE
Unreachable code in function with an empty return

### ISSUE THREAD

**Issue by jajik** [modcluster/mod_proxy_cluster#63]
Hello,

I have found this strange `if .. else` statement in the code.

https://github.com/modcluster/mod_proxy_cluster/blob/11f6f73f06c8d1ff62c16b6b8c67b47fb20fd73f/native/mod_proxy_cluster/mod_proxy_cluster.c#L1268-L1271

The function has some additional statements that are therefore unreachable. Is this a bug, or is it intended? If the latter, wouldn't it be better to omit the function completely as it does not do what it says? Or am I missing something?

It was introduced here  8576d58d82ba667ac703030f3b1852eab40f9547.

Thanks.

**Comment by rhusar** [comment]
Assigning @jfclere to clean this up. Thanks!

**Comment by jfclere** [comment]
that is obviously a bug!

**Comment by jfclere** [comment]
the:
+++
else 
     return; 
+++
Should be removed.

**Comment by jajik** [comment]
The else statement was removed.
