### ISSUE TITLE
Failing pipeline – wrong environment variable

### ISSUE THREAD

**Issue by jajik** [modcluster/mod_proxy_cluster#71]
The pipeline for the repository is currently failing. I believe it is due to a bad value of `APACHE_LOUNGE_DISTRO_VERSION` variable in Jenkins. The variable is currently set to `2.4.46`, but should be set to `2.4.57`.

It is used in [this](https://github.com/modcluster/ci.modcluster.io/blob/main/windows/mod_proxy_cluster/build.bat) script for downloading httpd.

I haven't found the way how to supply a different value with the push and I have not permissions to change it in Jenkins. Could someone look into it?

**Comment by jajik** [comment]
To be clear, it's here https://ci.modcluster.io/job/mod_proxy_cluster-2.x-windows/DISTRO=apache-lounge,label=w2k19/215/parameters.

**Comment by rhusar** [comment]
@jajik Changed the value now.

**Comment by jajik** [comment]
Great, thank you! The build part now passes, however the whole pipeline still fails due to some networking issues.

Closing issue as the variable is ok now.
