### ISSUE TITLE
mod_proxy_cluster.c send HTTP/1.0 requests

### ISSUE THREAD

**Issue by angifred** [modcluster/mod_proxy_cluster#80]
Hi,

Our security team as noticed that HTTP/1.0 requests are sent when using modcluster.

It is due to mod_proxy_cluster.c : in http_handle_cping_cpong method, we can see the request is built using the code "OPTIONS * HTTP/1.0\r\nUser-Agent: ".

I don't know well how it works, but perhaps "HTTP/1.0" should be changed into "HTTP/1.1" ?

Regards,
Frederic

**Comment by rhusar** [comment]
> Our security team as noticed that HTTP/1.0 requests are sent when using modcluster.

Can you please clarify why is that problematic? Having said that, I dont see a reason why not to use HTTP/1.1 in the `http_handle_cping_cpong` function.

**Comment by angifred** [comment]
They're afraid about http/1.0 ;-)

**Comment by jajik** [comment]
I would just note that httpd contains similar code; in `server/mpm_unix.c`

```c
data = apr_pstrcat(p, "OPTIONS * HTTP/1.0\r\nUser-Agent:
                   ap_get_server_description(),
                   " (internal dummy connection)\r\n\r\n", NULL);

```

**Comment by rhusar** [comment]
I meant to comment on this in the meantime - actually I think this is intentional, since HTTP 1.0 is just simpler and e.g. connections are by definition not persistent.

Can you @jfclere please confirm and/or close the issue?

**Comment by jfclere** [comment]
Actually Apache httpd sever code also used "HTTP/1.0".
HTTP/1.1 was added in 2.4.55 see https://httpd.apache.org/docs/2.4/mod/mod_proxy_hcheck.html
Adding a mod_proxy_cluster directive to allow HTTP/1.1 would be possible but that does make the connexion safer, using TLS and client certificates would make the connexion encrypted.
