### ISSUE TITLE
Clarify supported Apache httpd versions

### ISSUE THREAD

**Issue by jajik** [modcluster/mod_proxy_cluster#87]
Regarding the issue #86 it would be good to revisit requirements that mod_proxy_cluster has on httpd's version.

According to the [documentation](https://docs.modcluster.io/#requirements), the supported versions are 2.4.37 and newer, but that is not correct as the issue shows.

Should we just change the docs? Can we easily support 2.4.37? Should we add a job / modify one of existing jobs in CI to run against the oldest supported httpd to prevent future issues?

**Comment by rhusar** [comment]
> Regarding the issue #86 it would be good to revisit requirements that mod_proxy_cluster has on httpd's version.

+1

> According to the [documentation](https://docs.modcluster.io/#requirements), the supported versions are 2.4.37 and newer, but that is not correct as the issue shows.

That documentation pertains to 1.x version - we need to just update the requirement for 2.x. I can do that - so what is the minimal version we are going to support @jfclere ?

> Should we just change the docs? Can we easily support 2.4.37? Should we add a job / modify one of existing jobs in CI to run against the oldest supported httpd to prevent future issues?

I am personally not involved in httpd upstream to so I don't have hands on experience with what is a reasonable httpd version support matrix here. Clearly, we can't test every version and we should pick a narrow set (latest? oldest we support?)

So we currently test on CI:

* latest apache httpd version managed as part of https://github.com/modcluster/ci.modcluster.io/blob/main/httpd-dev/Containerfile
* latest available version in fedora https://github.com/modcluster/mod_proxy_cluster/blob/main/.github/workflows/ci.yml

Perhaps that's sufficient. Penny for your thoughts @jfclere

**Comment by jfclere** [comment]
Actually we support 2.4.53 and newer.

**Comment by rhusar** [comment]
Done.
