### ISSUE TITLE
Correct style, unsigned int and use constant when possible. 

### ISSUE THREAD

**Issue by jfclere** [modcluster/mod_proxy_cluster#92]
We are mixing
if (bla) { and if (bla)
int count, unsigned int count
some of the variable should be constant to make further development more easy.

**Comment by jajik** [comment]
Just to clarify, do we mind using `if` statements without brackets? I think it's ok without brackets.

The issue I had in #88 was mixing `if`/`else` where one branch has brackets and the other one does not. E.g.,

```cpp
if (bla)
    // do something
else {
    // do something else
}
```

If we want to enforce brackets in all cases, we can, but I think it's unnecessary...

**Comment by rhusar** [comment]
> Just to clarify, do we mind using `if` statements without brackets? I think it's ok without brackets.
> 
> The issue I had in #88 was mixing `if`/`else` where one branch has brackets and the other one does not. E.g.,
> 
> ```c++
> if (bla)
>     // do something
> else {
>     // do something else
> }
> ```
> 
> If we want to enforce brackets in all cases, we can, but I think it's unnecessary...

The code style https://github.com/modcluster/mod_cluster uses brackets always, I don't see the problem adopting the same in the httpd module code.

**Comment by jajik** [comment]
We can enforce it, but due to the rule where closing bracket of `if` is on a different line than `else`, we'll get

```c
if (bla) {
    foo();
}
else {
    bar();
}
```

instead of

```c
if (bla)
    foo();
else
    bar();
```

But ok, I'll create a PR where I fix the above and add a rule to .clang-format.

**Comment by jfclere** [comment]
I am like @rhusar: brackets everywhere  is better! let's enforce it!

**Comment by jajik** [comment]
TODO:
- [ ] `if`, `else` brackets
- [ ] use `unsigned` for countrs 
- [ ] use `unsigned` instead of `unsigned  int`
- [ ] some of the variable should be constant to make further development more easy.
